Add missing Link import to story page
Fixes TypeScript error: Cannot find name 'Link'
The Link component was being used but not imported from next/link